name: github_finder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  mobx: ^1.2.1+3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/  